# Generated by Django 4.2 on 2024-08-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_alter_pokemon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='picture',
            field=models.ImageField(default='trainer_images/default.jpg', upload_to='trainer_images'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('L', 'Lagartija'), ('T', 'Tierra'), ('P', 'Planta'), ('A', 'Agua'), ('F', 'Fuego'), ('E', 'Eléctrico')], max_length=30),
        ),
    ]
