# Generated by Django 4.2 on 2024-08-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0007_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('T', 'Tierra'), ('A', 'Agua'), ('F', 'Fuego'), ('L', 'Lagartija'), ('P', 'Planta'), ('E', 'Eléctrico')], max_length=30),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='picture',
            field=models.ImageField(upload_to='trainer_images'),
        ),
    ]
