# Generated by Django 4.2 on 2024-08-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0011_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('F', 'Fuego'), ('P', 'Planta'), ('A', 'Agua'), ('E', 'Eléctrico'), ('L', 'Lagartija'), ('T', 'Tierra')], max_length=30),
        ),
    ]
